### ISSUE TITLE
Admin unosi samo whitespace karaktere u nazivu template-a, te pojedinih polja, uspješno spremljen template

### ISSUE THREAD

**Issue by emir8gallo** [SoftverInzenjeringETFSA/SI2016_TIM2#1]
Komponenta:kreiraj-template.js 
Commit ID: bc0b03f13f6207ec2116c76079939015c0be3879 
Opis problema: Admin unosi samo whitespace karaktere u nazivu template-a, te pojedinih polja, uspješno spremljen template
Koraci za reproduciranje problema: 1. Pokrenuti aplikaciju; 2. Prijaviti se kao admin; 3. Odabir opcije kreiraj template. 4. Unos whitespace-ova u određena polja
Dobijeni rezultat: Uspješno kreiran template
Očekivani rezultat: Greška pri kreiranju template-a.

**Comment by haris-imamovic** [comment]
### > **BUG** 

_Napomena: Zbog nemogućnosti da postavimo labele primorani smo da označavanje postavljenih issue-a sprovedemo na ovaj način._
