### ISSUE TITLE
Moguće unijeti whitespace za username, ime i prezime

### ISSUE THREAD

**Issue by ebeus** [SoftverInzenjeringETFSA/SI2016_TIM2#10]
**Komponenta:** KorisnikService.java
commit ID: 36495a21c20e1cab7fc1a3d00ce6a71154790471
**Opis problema:** Moguće je registrovati korisnika sa whitespace znakom i unijeti whitespace za ime i prezime 

**Koraci za reproduciranje:** 
1. Pokrenuti aplikaciju 
2. Otvoriti registraciju
3. Upisati whitespace u polje korisničko ime, Ime i Prezime
4. Kliknuti na dugme “Registruj se”

**Dobijeni rezultati:** Nezaposleni korisnik je uspješno registrovan
**Očekivani rezultati:** Onemogućena registracija

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Riješeno.
