### ISSUE TITLE
Poslodavac se ne može registrovati

### ISSUE THREAD

**Issue by ebeus** [SoftverInzenjeringETFSA/SI2016_TIM2#11]
**Komponenta:** KorisnikService.java
commit ID: 36495a21c20e1cab7fc1a3d00ce6a71154790471

**Opis problema:** Korisnika tipa poslodavac nije moguće registrovati

**Koraci za reproduciranje:**
1. Pokrenuti aplikaciju 
2. Otvoriti registraciju
3. Unijeti validne podatke  (Registracija kao poslodavac)
4. Kliknuti na dugme “Registruj se”

**Dobijeni rezultat:** Ništa se ne desi
**Očekivani rezultati:** Poruka o nevalidnim podacima ili o uspješnoj registraciji, te redirekcija

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Popravljeno.
