### ISSUE TITLE
Moguća registracija sa postojećim e-mailom

### ISSUE THREAD

**Issue by ebeus** [SoftverInzenjeringETFSA/SI2016_TIM2#12]
**Komponenta:**  KorisnikService.java

commit ID: 36495a21c20e1cab7fc1a3d00ce6a71154790471

**Opis problema:** Moguće je registrovati se na postojeći mail

**Koraci za reproduciranje:** 
1. Pokrenti aplikaciju 
2. Otvoriti registraciju 
3. Unijeti podatke i e-mail koji već postoji

**Dobijeni rezultati:** Uspješna registracija
**Očekivani rezultati:** E-mail postoji, poruka da je došlo do greške

**Comment by haris-imamovic** [comment]
> **Documentation** - **Wontfix**

U SRS-u nigdje ne stoji da email korisnika mora biti jedinstven. Koliko god to imalo smisla, tehnički nije greška u softveru.
