### ISSUE TITLE
Unos nevalidnog datuma prilikom kreiranja oglasa prouzrokuje neadekvatnu poruku o grešci 

### ISSUE THREAD

**Issue by EdinBegic** [SoftverInzenjeringETFSA/SI2016_TIM2#13]
**Komponenta**: OglasController.java
**Commit** **ID**: 8c4e917ac0cd42cf431acf92273b9465d37950d1
**Opis problema**: Unosom nevalidnog datuma u polju ‘Trajanje oglasa’ ispisuje se neadekvatna poruka o grešci
**Koraci za reprodukciju problema**:

1. Pokrenuti aplikaciju
2. Prijaviti se kao poslodavac
3. Otvoriti podstranicu ‘Kreiranje oglasa’
4. Popuniti oglas s podacima koji uključuje nevalidan datum
5. Kliknuti na dugme ‘Dodaj’

**Dobijeni rezultat**: Prikaz bačenog izuzetka zajedno s path-om gdje se pojavljuje
![selection_032](https://cloud.githubusercontent.com/assets/17412256/26755861/b8cdaf3e-4896-11e7-9ae8-611df0e4c3b7.png)

**Očekivani rezultat**: Poruka o neispravnom unosu trajanja oglasa.

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Popravljeno.
