### ISSUE TITLE
Nedostatak pop-up-a koji traži potvrdu poslodavca o zatvaranju oglasa

### ISSUE THREAD

**Issue by EdinBegic** [SoftverInzenjeringETFSA/SI2016_TIM2#14]
**Komponenta**: viewad.hbs
**Commit ID**: dc788369898a02ff3cf5b96591e23941ca93bf00
**Opis problema**: Prema SRS-u potrebno je prikazati pop-up koji traži potvrdu od poslodavca da li želi da zatvori oglas, što ovdje nije implementirano
**Koraci za reprodukciju problem**:

1. Pokrenuti aplikaciju
2. Prijaviti se kao poslodavac
3. Otvoriti podstranicu ‘Moji oglasi’
4. Kliknuti na jedan od aktivnih oglasa
5. Kliknuti na dugme ‘Zatvori’

**Dobijeni rezultat**: Oglas je uspješno zatvoren.
**Očekivani rezultat**: Dodatni pop-up koji traži potvrdu poslodavca da li zaista želi zatvoriti oglas

**Comment by haris-imamovic** [comment]
> **BUG**
