### ISSUE TITLE
Moguć unos negativnog broja dana za produženje oglasa

### ISSUE THREAD

**Issue by EdinBegic** [SoftverInzenjeringETFSA/SI2016_TIM2#15]
**Komponenta**: viewad.hbs
**Commit ID**: dc788369898a02ff3cf5b96591e23941ca93bf00
**Opis problema**: Poslodavac unosi negativan broj dana kao vrijednost za koliko dana će se produžiti oglas , uspješna obnova oglasa 
**Koraci za reprodukciju problem**:

1. Pokrenuti aplikaciju
2. Prijaviti se kao poslodavac
3. Otvoriti podstranicu ‘Moji oglasi’
4. Kliknuti na jedan od zatvorenih oglasa
5. Unijeti negativan broj u polje ‘Broj dana’ na formi za obnovu oglasa
6. Kliknuti na dugme ‘Obnovi’

**Dobijeni rezultat**: Uspješno obnovljen oglas.

**Očekivani rezultat**: Zabrana obnavljanja oglasa te poruka o grešci.

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Popravljeno.
