### ISSUE TITLE
Prikazivanje poruke o uspješnom brisanju oglasa nakon izvršenja komande brisanja 

### ISSUE THREAD

**Issue by nejrabahtic** [SoftverInzenjeringETFSA/SI2016_TIM2#16]
Komponenta: oglasi-service.js

Commit ID: a8d6caa2b24d0228e1dbdf45138f36e6fdb01a61

Opis problema: Prema SRS-u nakon što se obriše oglas, nakon što administrator obriše oglas, potrebno je da se prikaže poruka o uspješnom brisanju oglasa, što ovdje nije implementirano.

Koraci za reprodukciju problem:
1. Pokrenuti aplikaciju 
2. Prijaviti se kao administrator 
3. Kliknuti na Oglasi 
4. Kliknuti na naziv nekog od oglasa 
5. Kliknuti na dugme Obriši u dijelu Brisanje oglasa 
6. Obrisati oglas

Dobijeni rezultat: Oglas samo biva obrisan, bez prikazivanja poruke

Očekivani rezultat: Nakon brisanja oglasa, prikazati poruku o uspješnom brisanju oglasa

**Comment by haris-imamovic** [comment]
> **BUG**
