### ISSUE TITLE
Poslodavac popunjava ključna polja oglasa sa whitespace karakterima te takav oglas spašava u bazu 

### ISSUE THREAD

**Issue by nejrabahtic** [SoftverInzenjeringETFSA/SI2016_TIM2#17]
Komponenta: dodaj-oglas.hbs

Commit ID: 15dc5e6697d555aec922d7ef676bb9475d7e1c7d

Opis problema: Poslodavac ključna polja oglasa popunjava sa whitespace karakterima te kao takav oglas biva spašen u bazu.

Koraci za reprodukciju problem:
1. Pokrenuti aplikaciju 
2. Prijaviti se kao poslodavac 
3. Otvoriti “Kreiranje oglasa” 
4. Popuniti ključna polja whitespace karakterima
5. Kliknuti na “Dodaj”

Dobijeni rezultat: Uspješno spašen oglas u bazu

Očekivani rezultat: Neuspješno spašavanje oglasa zbog whitespace karaktera

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Riješeno.
