### ISSUE TITLE
Problem sa vraćanjem template oglasa na defaultni

### ISSUE THREAD

**Issue by nejrabahtic** [SoftverInzenjeringETFSA/SI2016_TIM2#18]
Komponenta: dodaj-oglas.hbs

Commit ID: 555d838c47b46ced93965cb83ac4021a80982c8d

Opis problema: Ukoliko poslodavac izabere jednu vrstu template-a oglasa, prikazuju se dodatna polja karakteristična za taj template. Ukoliko se odluči za defaultni template, podstranica se ne refresuje s tim template-om.

Koraci za reprodukciju problem:
1. Pokrenuti aplikaciju 
2. Prijaviti se kao poslodavac 
3. Otvoriti “Kreiranje oglasa”
4. Izabrati “Template oglasa”
5. Promjeniti “Template oglasa” u defaultni
5. Refresh-ovati

Dobijeni rezultat: Iako smo promjenili template u defaultni, template je ostao isti

Očekivani rezultat: Pri promjeni u defaultni i refresh-ovanju, treba se prikazati defaultni template

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Popravljeno.
