### ISSUE TITLE
Podaci na interfejsu za slanje poruke ostaju isti nakon slanja poruke.

### ISSUE THREAD

**Issue by jbajramovi1** [SoftverInzenjeringETFSA/SI2016_TIM2#19]
Komponenta: pregled-korisnika.hbs

Commit ID: 0b4a865456c180bdce7469fb7b6194161eb1efbe

Opis problema: Nakon slanja poruke interfejs za isti ostaje isti s popunjenim podacima za prošlu poruku što može dovesti do spamanja korisnika.

Koraci za reprodukciju problem:
1. Pokrenuti apllikaciju
2. Otvoriti interfejs za slanje poruke
3. Upisati tekst poruke
4. Odabrati grafičku kontrolu za slanje poruke

Dobijeni rezultat: Podaci poslane poruke ostali na interfejsu za slanje poruka.

Očekivani rezultat: Nakon obavijesti o uspješno poslanoj poruci, tekst prethodne poruke se briše i otvara novi prozor.

**Comment by haris-imamovic** [comment]
> **WONTFIX**

Iako je dobra praksa resetovati formu nakon slanja, ovo ne dovodi do problema u sistemu. Očuvan je izgled interfejsa, funkcionalnost, te je ispoštovan SRS i dokument dizajna sistema u kojima se resetovanje forme ne navodi.
