### ISSUE TITLE
Admin kreira novi template s nazivom koji je vezan za spašeni template

### ISSUE THREAD

**Issue by emir8gallo** [SoftverInzenjeringETFSA/SI2016_TIM2#2]
Komponenta:kreiraj-template.js 
Commit ID: bc0b03f13f6207ec2116c76079939015c0be3879 
Opis problema: Admin kreira novi template s nazivom koji je vezan za spašeni template
Koraci za reproduciranje problema: 1. Pokrenuti aplikaciju; 2. Prijaviti se kao admin; 3. Odabir opcije kreiraj template. 4. Unos naziva template-a koji već postoji u bazi podataka
Dobijeni rezultat: Uspješno kreiran template
Očekivani rezultat: Greška pri kreiranju template-a.

**Comment by haris-imamovic** [comment]
> **Documentation** - **Wontfix**

U SRS-u nigdje ne stoji da naziv šablona mora biti jedinstven. Koliko god to imalo smisla, tehnički nije greška u softveru.
