### ISSUE TITLE
Vrijeme slanja poruke je za svaku poruku 00:00h.

### ISSUE THREAD

**Issue by jbajramovi1** [SoftverInzenjeringETFSA/SI2016_TIM2#20]
Komponenta: outbox.hbs

Commit ID: f728cec2139b9110290bfab2459f28163d5cd9cb

Opis problema: Za svaku dobijenu poruku, vrijeme slanje je 00:00h.

Koraci za reprodukciju problem:
1. Pokrenuti aplikaciju
2. Prijaviti se
3. Otvoriti tab Poruke
4. Vrijeme slanja primljene poruke za svaku poruku je 00:00h.

Dobijeni rezultat: Prilikom otvaranja dobijene poruke, vrijeme slanja je uvijek 00:00h.

Očekivani rezultat: Tačni podaci o vremenu slanja poruke.

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Popravljeno.
