### ISSUE TITLE
Implementirana skripta za bazu, ali nije prikazan jedan oglas iz skripte.

### ISSUE THREAD

**Issue by jbajramovi1** [SoftverInzenjeringETFSA/SI2016_TIM2#21]
Komponenta: tim2.sql

Commit ID: dc788369898a02ff3cf5b96591e23941ca93bf00

Opis problema:Implementirana skripta za bazu, ali nije prikazan jedan oglas iz skripte na interfejsu za aktivne oglase.

Koraci za reprodukciju problem:
1. Pokrenuti aplikaciju
2. Interfejs za prikaz oglasa

Dobijeni rezultat: Nisu prikazani svi oglasi iz skripte za bazu.

Očekivani rezultat: Prikazani svi oglasi na interfejsu namijenjenom za to.

**Comment by haris-imamovic** [comment]
> **Invalid**

Uvidom u stanje skripte vidimo da od tri postojeća oglasa jedan oglas je istekao. Sistem prikazuje samo dostupne oglase, odnosno one koju nisu istekli i koji nisu sakriveni.

![18902737_10212864748390522_1688070608_n](https://cloud.githubusercontent.com/assets/17404829/26765725/5acb2b22-4982-11e7-9abe-d64a6e23d01b.png)
