### ISSUE TITLE
Korisnički račun se ne briše na Firefox-u

### ISSUE THREAD

**Issue by ebeus** [SoftverInzenjeringETFSA/SI2016_TIM2#22]
**Komponenta:** KorisnikService.java

commit 25a61311fd841ddd3083c67046ae4a2b8151b834

**Opis problema:** Korisnički račun se ne izbriše na Firefoxu, dok se na Chrome (Chromiumu) obriše.
Prema SRS-u, pod 2.4.1 aplikacija radi na Firefoxu od verzije 52.0.

**Korisnički softver:**
* Linux Mint 18.1
* Firefox: 53.0 (64-bit)
* Chromium: Version 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

**Koraci za reproduciranje:**
1. Otvoriti stranicu u Firefox-u
2. Prijaviti se kao korisnik
3. Obrisati korisnički račun

**Dobijeni rezultati:** Korisnik je odjavljen ali korisnički račun nije obrisan, odnosno može se ponovo prijaviti

**Očektivani rezultat:** Korisnik se ne može prijaviti nakon što obriše račun

Dodaci:
![bug](https://cloud.githubusercontent.com/assets/17402990/26762337/ce316adc-4940-11e7-8582-48195bb194c8.gif)

http://imgur.com/a/sz18J

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Članovi našeg tima ne mogu rekreirati ovaj bug, odnosno brisanje prođe uspješno...
