### ISSUE TITLE
Admin unosi samo whitespace karaktere kao naziv kategorije, uspješno kreiranje kategorije

### ISSUE THREAD

**Issue by emir8gallo** [SoftverInzenjeringETFSA/SI2016_TIM2#3]
Komponenta: KategorijeService.java 
Commit ID: 552ff0e25e2b2f90e92f2a0c0fa65963a223032c 
Opis problema:Admin unosi samo whitespace karaktere kao naziv kategorije, uspješno kreiranje kategorije
Koraci za reproduciranje problema: 1. Pokrenuti aplikaciju; 2. Prijaviti se kao admin; 3. Odabir opcije dodaj  kategoriju. 4. Unos whitespace-ova u polje naziv kategorije
Dobijeni rezultat: Uspješno kreirana kategorija
Očekivani rezultat: Greška pri kreiranju kategorije.

**Comment by haris-imamovic** [comment]
### > **BUG** 

_Napomena: Zbog nemogućnosti da postavimo labele primorani smo da označavanje postavljenih issue-a sprovedemo na ovaj način._
