### ISSUE TITLE
Administrator mijenja naziv kategorije koristeći samo whitespace karaktere, naziv se uspješno mijenja

### ISSUE THREAD

**Issue by emir16949** [SoftverInzenjeringETFSA/SI2016_TIM2#4]
Komponenta: kategorija-service.js
commit ID: 8d3b5e5f99eae8b265dafac878ef208a3a9e1178
Opis problema: Administrator mijenja naziv kategorije koristeći samo whitespace karaktere, naziv se uspješno mijenja
Koraci za reproduciranje problema: 1. Pokrenuti aplikaciju 2. Prijaviti se kao administrator 3. Kliknuti na Kategorije oglasa 4. U dijelu Izmjena ili brisanje kategorije, naziv neke od kategorija izmijeniti tako da sadrži samo whitespace karaktere 5. Kliknuti na Izmijeni, dobija se poruka Uspješno ste izmijenili kategoriju
Dobijeni rezultat: Uspješno izmijenjen naziv kategorije
Očekivani rezultat: Greška pri izmjeni naziva kategorije - nevalidan naziv
Screenshot: http://pokit.org/get/?1bae634d44ee503ccfafa13ce68f9c44.jpg

**Comment by haris-imamovic** [comment]
> **BUG**  

_Napomena: Zbog nemogućnosti da postavimo labele primorani smo da označavanje postavljenih issue-a sprovedemo na ovaj način._
