### ISSUE TITLE
Administrator mijenja određenu kategoriju, nakon toga se ispisuje odgovarajuća poruka. Zatim, administrator briše drugu kategoriju, poruka o brisanju se ne prikazuje

### ISSUE THREAD

**Issue by emir16949** [SoftverInzenjeringETFSA/SI2016_TIM2#5]
Komponenta: kategorija-service.js
commit ID: 8d3b5e5f99eae8b265dafac878ef208a3a9e1178
Opis problema: Administrator mijenja određenu kategoriju, nakon toga se ispisuje odgovarajuća poruka. Zatim, administrator briše drugu kategoriju, poruka o brisanju se ne prikazuje
Koraci za reproduciranje problema: 1. Pokrenuti aplikaciju 2. Prijaviti se kao administrator 3. Kliknuti na Kategorije oglasa 4. U dijelu Izmjena ili brisanje kategorije, izmijeniti naziv neke od kategorija 5. Kliknuti na Izmijeni, dobija se poruka Uspješno ste izmijenili kategoriju 6. Kliknuti na dugme Izbriši ispod naziva neke od kategorija 7. Kategorija se briše, ali se ne prikazuje poruka o brisanju kategorije, već ostaje stara poruka o promjeni naziva kategorije
Dobijeni rezultat: Obrisana kategorija, nema nikakve poruke o brisanju
Očekivani rezultat: Obrisana kategorija, uz adekvatnu poruku o brisanju
Screenshot: http://pokit.org/get/?7cf915ff6aaf357addfae351b1f23669.jpg
http://pokit.org/get/?069829e6a90bc78752adb8ab385441aa.jpg
http://pokit.org/get/?c4ff97e9605ddfc7c63116cae1a1d171.jpg

**Comment by haris-imamovic** [comment]
>**BUG**
