### ISSUE TITLE
Nakon što administrator pritisne odgovarajuće dugme za brisanje oglasa, potrebno je da se pojavi pop-up sa pitanjem o potvrdi brisanja, a isti se ne pojavi

### ISSUE THREAD

**Issue by emir16949** [SoftverInzenjeringETFSA/SI2016_TIM2#6]
Komponenta: oglasi-service.js
commit ID: a8d6caa2b24d0228e1dbdf45138f36e6fdb01a61
Opis problema: Prema SRS-u, nakon što administrator pritisne odgovarajuće dugme za brisanje oglasa, potrebno je da se pojavi pop-up sa pitanjem o potvrdi brisanja, što ovdje nije implementirano
Koraci za reproduciranje problema: 1. Pokrenuti aplikaciju 2. Prijaviti se kao administrator 3. Kliknuti na Oglasi 4. Kliknuti na naziv nekog od oglasa 5. Kliknuti na dugme Obriši u dijelu Brisanje oglasa 6. Oglas se briše, ali bez ikakvog pop-up menija.
Dobijeni rezultat: Nakon klika na dugme Obriši, oglas obrisan bez ikakve potvrde o brisanju
Očekivani rezultat: Nakon klika na dugme Obriši, prikaz pop-up menija o potvrdi brisanja
Screenshot: http://pokit.org/get/?e5eaa596a76a7efba5f83a70743f104c.jpg
http://pokit.org/get/?87fb0a78fdd2d3c4939a1aa2a29cd471.jpg

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Popravljeno.
