### ISSUE TITLE
Profilni podaci izmijenjeni unosom samo whitespace karaktera, profil uspješno ažuriran.

### ISSUE THREAD

**Issue by seilabecirovic** [SoftverInzenjeringETFSA/SI2016_TIM2#7]
**Komponenta:** profile.js
**commit ID:** 414908c8dd5261e9d4938055019f57aa12af5865
**Opis problema:** Profilni podaci izmijenjeni unosom samo whitespace karaktera, profil uspješno ažuriran 
**Koraci za reproduciranje problema:** 
1. Pokrenuti aplikaciju 
2. Prijaviti se kao korisnik (nezaposleni) 
3. Klikom na username se dolazi do izmjene 
4. Za odgovarajuće podatke Ime, Prezime, CV se unosi whitespace karakter. 
5. Kliknuti na dugme Spasi izmjene

**Dobijeni rezultat:** Uspješno ažuriran profil
**Očekivani rezultat:** Greška pri izmjeni podataka profila se prijavljuje, na osnovu SRS-a.
**Screenshot:**
![screenshot from 2017-06-03 17-30-06](https://cloud.githubusercontent.com/assets/17402968/26755262/2e961772-488a-11e7-8d92-1eabfd34ec2e.png)

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Riješeno.
