### ISSUE TITLE
Unos maila postojećeg korisnika kod izmjene profila, profil uspješno ažuriran.

### ISSUE THREAD

**Issue by seilabecirovic** [SoftverInzenjeringETFSA/SI2016_TIM2#8]
**Komponenta:** KorisnikService.java
**commit ID:** 414908c8dd5261e9d4938055019f57aa12af5865
**Opis problema:** Unos maila postojećeg korisnika kod izmjene profila, profil uspješno ažuriran.
**Koraci za reproduciranje problema:** 
1. Pokrenuti aplikaciju 
2. Prijaviti se kao korisnik (nezaposleni) 
3. Klikom na username se dolazi do izmjene 
4. Unijeti izmjenjene podatke - mail isti kao postojeći mail drugog korisnika 
5. Kliknuti na dugme Spasi izmjene

**Dobijeni rezultat:** Uspješno ažuriran profil
**Očekivani rezultat:** Greška pri izmjeni podataka profila se prijavljuje, na osnovu SRS-a.
**Screenshots:**
![selection_016](https://cloud.githubusercontent.com/assets/17402968/26755284/9f00d3a8-488a-11e7-8fe4-254215c94598.png)
![selection_017](https://cloud.githubusercontent.com/assets/17402968/26755286/a5328366-488a-11e7-814f-fa853d2b9703.png)
![selection_018](https://cloud.githubusercontent.com/assets/17402968/26755289/a8e167de-488a-11e7-87d3-321c77c01696.png)

**Comment by haris-imamovic** [comment]
> **Documentation** - **Wontfix**

U SRS-u nigdje ne stoji da email korisnika mora biti jedinstven. Koliko god to imalo smisla, tehnički nije greška u softveru.
