### ISSUE TITLE
Nije implementiran unos password-a za brisanje računa.

### ISSUE THREAD

**Issue by seilabecirovic** [SoftverInzenjeringETFSA/SI2016_TIM2#9]
**Komponenta:** profile.hbs
**commit ID:** e801ecca1951258bf25d4f91cd1c2af808daa08f
**Opis problema:** Prema SRS-u korisnik mora unijeti dodatno svoj password da bi mogao izbrisati svoj račun, što u ovom slučaju nije implementirano.
**Koraci za reproduciranje problema:** 
1. Pokrenuti aplikaciju 
2. Prijaviti se kao korisnik (nezaposleni) 
3. Klikom na username se dolazi do izmjene 
4. Odabrati opciju brisanja 
5. Kliknuti na dugme za brisanje

**Screenshot:**
![selection_014](https://cloud.githubusercontent.com/assets/17402968/26755310/097af574-488b-11e7-8307-91b8e1b91dca.png)

**Comment by haris-imamovic** [comment]
> **BUG**

**Comment by edoimamovic** [comment]
Riješeno.
